- pywwt_web/jupyter_widget.py
- setup.py
Fixes https://github.com/astrofrog/pywwt-web/issues/15
> Use ipyevents to try and prevent scrolling issues

- pywwt_web/core.py
(addition to core.py as mentioned on Slack today)
> Added missing setting to core.py

- pywwt_web/core.py
- pywwt_web/qt_widget.py
- pywwt_web/static/wwt_json_api.js
@ojustino - just so you are aware, I've added a few methods related to the foreground/background. With this, you can see what imagery is available by checking ``wwt.available_layers`` and then set the foreground/background with e.g. ``wwt.foreground = ...``
> Added methods to load the image collection and set foreground/background

- pywwt_web/annotation.py
- pywwt_web/core.py
- pywwt_web/static/wwt_json_api.js
Did I create the classes for the shapes correctly?
> Trying shape settings and methods in annotation.py [issue #2]

- .travis.yml
- appveyor.yml
- pywwt_web/core.py
- pywwt_web/imagery.py
- pywwt_web/qt_widget.py
- pywwt_web/static/wwt_json_api.js
- setup.py
@ojustino - just so you are aware, I've added a few methods related to the foreground/background. With this, you can see what imagery is available by checking wwt.available_layers and then set the foreground/background with e.g. ``wwt.foreground = ...``
> Add methods to control foreground/background

- pywwt/qt_widget.py
This will now show the logging messages from javascript when using WebKit
> Improve logging from javascript

- .travis.yml
- pywwt/annotation.py
- pywwt/core.py
- pywwt/traits.py
- setup.py
Color validators and comment removal coming next.
> Added validators for circle radius and all linewidths

- js/lib/wwt.js
- pywwt/annotation.py
- pywwt/core.py
- pywwt/static/wwt.html
- pywwt/tests/test_core.py
The defaults weren't initialized correctly at startup
> Fix issues with Jupyter widget

- appveyor.yml
(AppVeyor is a CI service that runs our tests on Windows)
> WIP: Fix AppVeyor build

- pywwt/annotation.py
- pywwt/core.py
- pywwt/jupyter.py
- pywwt/qt.py
I tried to cover everything on [this page](http://pywwt.readthedocs.io/en/latest/api.html) and all of the subsequent links besides Windows.
> Docstrings

- pywwt/core.py
- pywwt/static/wwt.html
Host surveys catalog ourselves so that we can use https
> Fix image collection URL

- pywwt/tests/test_qt_widget.py
This includes a change that makes it easy to download the actual and expected images locally - basically there will now be a script printed in the log in case of failure that when copied/pasted locally will allow the actual and expected images to be re-generated (rather than trying to reproduce the exact same failure locally).
> Make it easier to diagnose CI issues

- wwtsdk.js
From http://worldwidetelescope.org/html5sdk/2.0/wwtsdk.js
> Updated to latest WWT SDK

- pywwt/core.py
> Available modes property

- docs/annotations.rst
I didn't add an example because of the current issue with creating annotations that I mentioned last week.
> Wrote CircleCollection docs

- pywwt/annotation.py
@ojustino - I've updated the wwtsdk.js file we use to use the currently staged version which fixes annotations (with the exception of the radius for circles in display units and colors). Lines and the auto-refreshing now works.
> Remove code that is no longer necessary

- README.rst
If there is more that should be added, please let me know.
> Wrote branch-specific README

- pywwt/nbextension/static/wwt_json_api.js
A one line change that prevents error read-outs for older versions of Qt.
> Made wwt_json_api.js function compatible with Qt

- docs/layers.rst
- pywwt/core.py
- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
- pywwt/qt.py
- pywwt/tests/test_layers.py
- pywwt/tests/test_qt_widget.py
Fixes #132
This does not solve #125 because it seems like the JS call doesn't have any effect so far, so we still need to fix that. But the Python API is in place.
> Add layer manager and way to remove layers

- .coveragerc
- .travis.yml
- appveyor.yml
- docs/layers.rst
- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
- pywwt/tests/test_layers.py
This adds support for specifying the altitude type (Fixes #128), automatically determining the units for altitude and longitude (Fixes #127), as well as manually setting the altitude and longitude units.
I've also added coverage testing and added a workaround for the refresh issue with layers (basically I temporarily change the color to black and back after changing any layer attribute).
> More layer improvements

- pywwt/nbextension/static/wwt_json_api.js
Just make them transparent instead for now!
> Add workaround for removing layers

- pywwt/nbextension/static/wwt_json_api.js
This was an oversight after implementing the opacity
> Fix setting of color

- pywwt/core.py
- pywwt/nbextension/static/wwt_json_api.js
This consists of a couple of new functions in `core.py` and corresponding entries in `wwt_json_api.js`.
> Wrote in ability to pause/play time

- docs/index.rst
Some language changes, and change the initial screenshot to show Kepler exoplanet data, which is the kind of thing that will get research astronomers a bit more excited than constellations.
> docs/index.rst: tweak a little bit

- pywwt/layers.py
- pywwt/tests/test_layers.py
We can obviously improve this over time, but this should at least catch some common issues such as https://github.com/WorldWideTelescope/pywwt/issues/154
Fixes https://github.com/WorldWideTelescope/pywwt/issues/154
> Try and guess which column to use for lon/lat

- docs/annotations.rst
- docs/layers.rst
- docs/settings.rst
- render() is only available on Qt
- set_view('solar system'), not 'solar_system'
- missing parenthesis
- available_layers is an attribute, not a method
> docs: minor polish

- docs/index.rst
- docs/installation.rst
> docs: update mybinder links to track reorganization

- CHANGES.rst
- pywwt/nbextension/static/wwt_json_api.js
> Fix refresh issues and make sure any guessing from WWT related to columns is ignored

- docs/installation.rst
@pkgw - this works for me, is this also what you had to do to get Jupyter Lab to work?
Fixes #169
> Added note about using Jupyter Lab

- CHANGES.rst
- pywwt/nbextension/static/wwt_json_api.js
Undefined columns should have a value of -1
> Fixed an issue with layers not appearing under certain circumstances

- setup.py
A packaging fix from my demo branch that never made it into the mainline.
> setup.py: install new interactive figure resource files

- README.rst
- docs/index.rst
We should acknowledge the NSF here. Acknowledgment also added to docs/index.rst. Also general revision of the intro content.
> README.rst: revamp and acknowledge the NSF

- README.rst
- docs/index.rst
- docs/installation.rst
- docs/jupyter.rst
- docs/qt.rst
- docs/settings.rst
- docs/views.rst
- docs/windows.rst
- examples/jupyter/example.ipynb
- examples/windows/pywwt_example.ipynb
- package.json
- pywwt/core.py
- pywwt/jupyter.py
- setup.py
- Update/fix links to Binder instances
- More aggressive AAS branding
> More work on branding and the docs landing page

- pywwt/annotation.py
- pywwt/layers.py
- pywwt/utils.py
Settling a to-do item in `layers.py`.
> Added validation for frames in TableLayer

- CHANGES.rst
- RELEASE.rst
- docs/conf.py
- lib/wwt.js
- package.json
- pywwt/_version.py
- pywwt/jupyter.py
This PR includes the commit that will become identified with v0.7.0, and also the bump back to the new development series of 0.8.0.dev0. Will push the release tag and `v0.7.x` branch after the PR is merged.
> Release 0.7

- docs/index.rst
Here are my proposed changes to the Binder links on our docs' index page.
> Changed Binder links on index page of docs

- .github/pull_request_template.md
(let's try eating our own dogfood ...)
Add a GitHub pull request template file to try to encourage us to dot all of the i's and cross all of the t's.
*None of these apply to this PR IMO, but I'm leaving them in this case to demonstrate the proposed changes.*
*For the future: PEP8 formatting, copyright assignment, ...?*
> .github/pull_request_template.md: add this

- wwtsdk.js
This is necessary to fix the drawing of colormapped data tables when there are NaNs.
(*no standard checklist items apply here*)
> wwtsdk.js: update to wwt-web-client 47d9e49

- wwtsdk.js
This fixes some potential showstopping null derefs with image colormaps.
Closes #251.
(*no checklist items relevant for this PR*)
> wwtsdk.js: update to wwt-web-client 101727ad

- README.rst
- pywwt/tests/test_layers.py
Just updating the CI badges to reflect the use of Azure.
> Update CI badges

- docs/index.rst
As it says: revise the BinderHub links for the new organization of that repo.
N/A for the first two, not worth logging in CHANGES.
> docs/index.rst: revise the binder links for the new repo organization

- README.rst
Add links to the BinderHub at the top of the README.rst
N/A to all three.
> README.rst: add binder links at the top here

- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/layers.rst
- docs/settings.rst
- docs/views.rst
- docs/windows.rst
- examples/windows/pywwt_example.ipynb
- pywwt/windows/client.py
- pywwt/windows/layer.py
Fix the CI due to evolving docs links.
None applicable.
> Fix up the CI

- .gitignore
- wwtsdk.js
Update pywwt's copy of the WWT engine to @wwtelescope/engine 7.1.1. The only compat break is the relocation of the `ss` ScriptSharp support module, which is not referenced in pywwt, so we shouldn't break existing installations.
This *should* get pywwt working over HTTPS for free, thanks to the improvements to the underlying engine's protocol handling logic.
N/A for gh-pages changes.
> Update the pywwt copy of the SDK to @wwtelescope/engine 7.1.1

- wwtsdk.js
Get some bugfixes including important ones for WWT Ambassadors projects, which
use this copy of the SDK.
> wwtsdk.js: update to @wwtelescope/engine 7.4.0

- CHANGES.rst
- README.rst
- docs/index.rst
- pywwt/annotation.py
- pywwt/core.py
- pywwt/nbextension/static/interactive_figure/index.html
- pywwt/nbextension/static/interactive_figure/interactive_figure.js
- pywwt/nbextension/static/wwt.html
Point to mybinder.org instead of our private binder, and update the HTML files to get the SDK from web.wwtassets.org, not the pywwt GitHub Pages instance.
> Use mybinder.org and web.wwtassets.org

- CHANGES.rst
- package.json
- pywwt/_version.py
- pywwt/jupyter_server.py
Fix JupyterHub single-user mode and release 0.9.0.
Gah I have no idea how to automate testing of the JHub fix :-(
> Fix JupyerHub singleuser; 0.9.0

- pywwt/tests/test_layers.py
I thought that I could get away with impatience on a couple of macOS tests, but now I think not.
> Yet more CI robustness work

- README.md
Mention the FastTract NSF grant in the README.
N/A
> README.md: mention the FastTract grant

- pywwt/nbextension/static/interactive_figure/interactive_figure.js
- pywwt/nbextension/static/wwt_json_api.js
Slight changes for this PR
https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/96/
> Companion patch to WebGL FITS engine release

- pywwt/core.py
- pywwt/jupyter.py
- pywwt/qt.py
Tidy up a few things now that we're all on the same page with the app. Mostly doing this to start getting a sense of the reliability of the CI ...
> Mop-ups from the app transition

- docs/installation.rst
- docs/jupyterlab.rst
- pywwt/jupyter.py
Update the docs to reference the Kernel Data Relay, which is now an important part of the Jupyter(Lab) experience.
> Some docs work

- frontend/package.json
This version adds support for specifying names with imageset layers when they're loaded.
> frontend/package.json: require version 0.9.2 of the research app

- pywwt/layers.py
- setup.py
- Replaced the parameters force_tan etc. with a TilingMethod enum
- Array/wcs input is now sent to TOASTY for tiling if the input is big enough
- Added option to set start level for TOAST creation
Requires https://github.com/WorldWideTelescope/toasty/pull/86
> Update for FITS TOAST and toasty 0.18

- .readthedocs.yaml
- .readthedocs_env.yml
- ci/azure-build-and-test.yml
Keep the CI running.
- [n/a] Changed code has some test coverage (or justify why not)
- [n/a] Changes in functionality documented (or justify why not)
> CI updates

- ci/zenodo.json5
This will allow subsequent releases to be properly chained in Zenodo's record-keeping.
> ci/zenodo.json5: update this with pywwt's Zenodo "concept" record ID

- README.md
- ci/zenodo.json5
in response to https://github.com/WorldWideTelescope/pywwt/pull/340#issuecomment-1292423409
> ORCID entry for dhomeier

- ci/azure-build-and-test.yml
- ci/azure-job-setup.yml
- ci/azure-sdist.yml
Fix CI; Linux scipy installs were complaining about a lack of OpenBLAS dev files. Build succeeded recently and our code hasn't changed, so I think the OS images must have changed.
- [N/A] Changed code has some test coverage (or justify why not)
> Fix up Linux CI

- .readthedocs.yaml
- .readthedocs_env.yml
- ci/azure-build-and-test.yml
- setup.py
Trying to fix the readthedocs build, yet again.
> .readthedocs.yaml: attempt to fix this

- setup.py
Update the "front door" email address to hello@worldwidetelescope.org, and some other updates to setup.py that I noticed were needed.
This is yet another part of the sponsorship migration.
Related pull requests cross-linked at: https://github.com/WorldWideTelescope/worldwidetelescope.github.io/pull/88
- [N/A] Changed code has some test coverage (or justify why not)
> Update the "front door" email address to hello@worldwidetelescope.org

- pyproject.toml
This makes sure that installing the next release of pywwt will require the latest version of the frontend, which will require the new ESM version of the engine.
Since we build the frontend code and distribute that version of the research app as part of the build process, this is mostly a belt-and-suspenders thing, but might as well do it properly.
- [N/A] Changed code has some test coverage (or justify why not)
> pyproject.toml: have the Python package require the latest version of the frontend

- ci/azure-deployment.yml
- ci/azure-sdist.yml
Cranko has been fixed up to work with Zenodo again, so we can turn DOI registration back on.
- [N/A] Changed code has some test coverage (or justify why not)
> Re-enable Zenodo deposition

- surveys.xml
> Add DECaPS2 to default pywwt surveys
