- pywwt_web/core.py
On [line 28](https://github.com/ojustino/pywwt-web/blob/force-traits/pywwt_web/core.py#L28), `_on_trait_change()` calls [WWTQtWidget's `_send_msg()` method from qt_widget.py](https://github.com/ojustino/pywwt-web/blob/force-traits/pywwt_web/qt_widget.py#L140). However, when using the new [`for` loop on line 14](https://github.com/ojustino/pywwt-web/blob/force-traits/pywwt_web/core.py#L15), I get `AttributeError: 'WWTQtWidget' object has no attribute 'widget'`. For some reason it's not accessing the definition for `self.widget` [in the WWTQtWidget class' `__init__()` method from qt_widget.py](https://github.com/ojustino/pywwt-web/blob/force-traits/pywwt_web/qt_widget.py#L125) and I can't figure out why.
> Initial try fixing core.py initialization bug

- pywwt/core.py
- pywwt/imagery.py
- pywwt/static/wwt_json_api.js
I don't know if this is intentional, but `play_tour()` resumes playback immediately while `stop_tour()` slows the tour down to a stop over the course of a few seconds.
> Added methods to load/control tours [issue #4]

- pywwt/core.py
- pywwt/quantity_trait.py
1) I had to change the trait types from float to Any, but the unit check a) makes sure `proposal` is an astropy quantity, and b) raises an error if it's not the right type of quantity. Given that traitlets doesn't include data types with units, is this an acceptable workaround? 
2) Do you think it should still be possible for proposal to be a float and users have the option to choose which type they prefer? If it's a float, we could turn the unit check into an `elif` and first check if `proposal` is a float. 
3) What effect is location_altitude supposed to have in the widget? I see no discernible changes in the picture, even at Everest-level heights.
4. Is there a way to include all units of length for `location_altitude`? `find_equivalent_units()` was the best I found in astropy, but it …
> Making local traits take astropy quants [issue #25]

- pywwt/static/wwt_json_api.js
@ojustino - just for information, this fixes the drawing of the circles (and other shapes). The issue was that the ``switch(msg['shape'])`` clause was missing ``break``s after each section, which meant that all the clauses got run when adding a circle, in turn causing issues.
> Fix drawing of annotations

- CHANGES.rst
- js/lib/index.js
- js/lib/wwt.js
- js/package.json
- pywwt/__init__.py
- pywwt/jupyter.py
- pywwt/jupyter_server.py
- pywwt/static/wwt.html
- setup.cfg
This is just an experimental branch as I'm at a Jupyter widgets workshop this week.
Things to do/figure out:
> Proper support for Jupyter lab

- CHANGES.rst
- pywwt/core.py
- pywwt/jupyter.py
This adds GUI controls for setting the foreground, background, and foreground opacity. These controls can be shown by doing ``wwt.layer_controls``. I want to add a mention of this to the docs. We could also decide to show these by default with the WWT widget, but some users might not want it so it could be an option.
**Preview:**
> Added GUI controls for layers

- CHANGES.rst
- js/lib/wwt.js
- pywwt/jupyter.py
When WWT is moved to a separate panel in Jupyter Lab, it will now get resized correctly. However, the approach here is somewhat hacky and some things should probably be fixed upstream to make some of these things easier, so will open an issue in the Jupyter Lab repo.
> Fix resizing of WWT in Jupyter Lab

- pywwt/static/wwt.html
This now uses the latest SDK from http://worldwidetelescope.org/html5sdk/2.0/wwtsdk.js
> Update WWT SDK URL

- pywwt/core.py
- pywwt/layers.py
Here's my method to a) allow users to tab complete layer names, and b) automatically sort new layers by wavelength band.
I combined your proof-of-concept with regular expressions to look for key words in the strings that comprise the layer names ('UV', 'microwave', etc.). This way, if a user decides to upload more layers, they'll automatically be sorted.
I also use regular expressions to shorten the layer names and specifically change '2MASS' to 'twomass'. I also read about a package that converts integers to their string representations (e.g. 6 to 'six'); let me know if you want me to integrate into `layers.py` as well.
Then, I add one line to `core.py`, and it allows for layers to be changed like so:
`wwt.foreground = wwt.imagery.x.rass`.
I'm not sure how to check if properties show up …
> Attempted solution for tab completing layers

- pywwt/core.py
It was previously performing a check on the traitlets object as a whole instead of just its `value` attribute.
> Made quick fix for ss_scale error

- docs/settings.rst
- docs/views.rst
- pywwt/core.py
- pywwt/nbextension/static/wwt.html
- pywwt/ss_proxy.py
Is it OK that tab-completion also shows the inherited methods from traitlets' `HasTrait` along with the solar system traits?
Edits to the docs are upcoming.
> Moved solar system settings to proxy object

- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
- pywwt/tests/test_layers.py
This provides a way of updating layer data (rather than having to delete and re-create a layer). It also sets the astronomical mode when the frame is ``Sky`` and provides a way to set the opacity, although the first requires two changes to the web client SDK to work properly (https://github.com/WorldWideTelescope/wwt-web-client/pull/182 and https://github.com/WorldWideTelescope/wwt-web-client/pull/183) and the latter doesn't actually have any effect on the WWT side yet as WWT seems to ignore opacity.
> More layer improvements

- pywwt/nbextension/static/wwt.html
- pywwt/ss_proxy.py
Namely, `set_solarSystemMinorOrbits` (orbit paths of non-featured moons, satellites, etc.) and `set_solarSystemStars` (background stars) in solar system mode. I also changed `solarSystemStars` to be on by default.
`set_solarSystemMinorPlanets` is also available now, but there are so many that it overloaded my RAM and crashed my session. In order to avoid this outcome for users, I've left it commented out.
> Exposed a couple of features after SDK update

- CHANGES.rst
- pywwt/core.py
- pywwt/nbextension/static/wwt.html
I think things look prettier without the crosshair by default, and it's easy for people to add it if needed.
> Disable crosshairs by default

- pywwt/core.py
- pywwt/layers.py
This partially addresses https://github.com/WorldWideTelescope/pywwt/issues/97
I say partially because for now we don't have a way to select the different earth maps available, which I suggest we focus on after this release. I think with this PR the default will at least be more sensible.
> Set default earth map to daytime

- CHANGES.rst
- docs/index.rst
- docs/shortcuts.rst
- pywwt/nbextension/static/wwt.html
`z` to zoom in, `x` to zoom out. Any suggestions about zoom speed or smoothness?
There's still some debugging code in case I need to make changes, but this should work in both the Qt and Jupyter versions. Qt's web browser's standards aren't up-to-date as those of Chrome/Firefox/etc., so I had to add backwards compatibility to accommodate for that.
Now that I've figured out the problem with Qt, it seems like it wouldn't be difficult to add other keyboard controls.  Would that be useful?
> Keyboard-controlled zoom

- CHANGES.rst
- pywwt/nbextension/static/wwt.html
Since https://github.com/WorldWideTelescope/pywwt/pull/81, the two finger scroll results in a different behavior from the WWT web client (the axis direction is inverted) and the scrolling can be jumpy at times. Removing this block of code restores the original behavior. It seems this isn't needed for the keyboard shortcuts?
> Don't override default wheel behavior

- CHANGES.rst
- docs/layers.rst
- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
This implements the ability to specify whether marker size is relative to the screen or the world coordinates, as well the the marker type (although see https://github.com/WorldWideTelescope/wwt-web-client/issues/191 for a description of issues related to that).
This also adds a workaround for https://github.com/WorldWideTelescope/wwt-web-client/issues/189 which means that plotting relative to e.g. the Sun and bodies other than the Earth will work correctly when the altitude/distance is provided.
Finally, this exposes the option to show/hide points on the far side of an object (see https://github.com/WorldWideTelescope/wwt-web-client/issues/190 for what I think is an issue with the default setting of ``False``).
> Further improvements to layers

- recipes/pywwt/meta.yaml
- recipes/pywwt/post-link.bat
- recipes/pywwt/post-link.sh
- recipes/pywwt/pre-unlink.bat
- recipes/pywwt/pre-unlink.sh
I think these are no longer needed, though we'll see based on the ``run_test.py``
> Remove post/pre scripts

- CHANGES.rst
- pywwt/layers.py
- pywwt/nbextension/static/wwt.html
- pywwt/solar_system.py
This exposes the option to turn the large-scale SDSS data on/off since this now works in the SDK. I'm going to include it in a small bug fix release because it currently causes the performance to be quite poor when in Milky Way mode, and I need a way to turn it off in glue.
> Expose option to control large-scale SDSS data

- docs/index.rst
- docs/installation.rst
I thought I had already fixed the typo in the aas.org link, but I guess not.
> docs: fix and update some links

- pywwt/conftest.py
- pywwt/tests/test_layers.py
This is just an experimental PR to try different things to fix the CI
> Fix CI issues

- pywwt/jupyter_server.py
Version 5.7.6 of the Jupyter notebook module adds a new security feature related to the HTTP content types (https://github.com/jupyter/notebook/issues/4467#issuecomment-471353499). It breaks pywwt because pywwt has not been returning valid MIME types (AKA content types) from its internal Jupyter server.
From looking at the main `notebook` implementation, it seems that the correct approach is to use the `mimetypes` module to get the right value to put in the Content-Type header, so let's go ahead and do that.
Closes #191.
> Fix pywwt on `notebook >=5.7.6`

- pywwt/qt.py
This is needed for glue and any other application that might want to embed the Qt WWT widget - basically this provides a way for the parent application to define custom drag and drop behavior.
> Pass drag and drop up to parent in Qt widget

- pywwt/layers.py
- pywwt/tests/test_layers.py
The method name `add_data_layer()` may be deprecated, but to maintain compatibility we should still actually do something. So, fall back to `add_table_layer()` when called. This fixes glue-wwt, which hasn't been updated to the new API yet.
> pywwt/layers.py: have `add_data_layer()` fallback to `add_table_layer()`

- .travis.yml
- appveyor.yml
- docs/windows.rst
- pywwt/annotation.py
- pywwt/core.py
- pywwt/windows/client.py
- pywwt/windows/layer.py
If we use semicolons, errors in the middle of the pipeline can get swallowed. Using `&&` makes sure that we catch them.
> .travis.yml: don't use semicolons in Travis shell commands

- docs/installation.rst
- setup.py
This version separates out the "web engine" code into a separate package that must also be installed.
Closes #204.
> Fix ReadTheDocs build for PyQt5 >= 5.12

- docs/conf.py
- docs/installation.rst
Including a fun problem that the server for GitBook.io returns more than 100 HTTP headers, which Python doesn't like.
> docs: fix link-checking

- pywwt/jupyter_server.py
The python mimetype library does not include the MIME type information for FITS files by default, so we have to add it. Otherwise adding FITS images breaks pywwt on notebooks 5.7.6 and up. (See #191 and #192 for more info on notebooks and MIME types)
> Add FITS MIME type

- lib/wwt.js
- pywwt/core.py
- pywwt/jupyter.py
- pywwt/nbextension/static/wwt_json_api.js
- pywwt/qt.py
Part of the work needed to implement issue #200. This uses traitlets to connect the jupyter widget's properties back into the python class.
> Fix get_center method for the jupyter widget and add a get_fov method for both widgets

- pywwt/layers.py
- pywwt/tests/test_layers.py
Windows would not display table layers due to the way we were previously normalizing line endings for WWT. This PR fixes that problem.
> Fix Table Layer issue in Windows

- .travis.yml
- appveyor.yml
- pywwt/core.py
- setup.py
Fixes a couple of issues I found in the reset method:
1. Only half of the layers were removed when resetting the widget.
2. An exception was thrown when resetting the jupyter widget because we were also resetting the inherited DOMWidget traits.
> Fix widget reset bugs

- appveyor.yml
- pywwt/conftest.py
- pywwt/tests/test_qt_widget.py
When I added the hack to get Python 3.6 running on our AppVeyor Windows CI, I think everything passed, but now we get different images in our testing framework. At the moment, the version-constrained CI uses WebKit as its rendering engine instead of WebEngine.
The hack was to fix the version of pyqt to avoid a library incompatibility issue, so let's try applying that constraint *everywhere*, which will hopefully get all of the Windows tests using WebKit. Then we can modify the test images to match the differences between the two engines.
> Try to get Windows CI working again

- lib/wwt.js
I need this in version 0.35.6.
(The diff looks gnarly but it's mostly indentation; there's some control flow rearrangement, but the action is basically in the revised first stanza.)
> Fix separate-pane resizing in recent JupyterLab

- pywwt/jupyter_server.py
When we're serving up files in JupyterHub, we need to include the notebook server's base_url in the URL we generate. This is obnoxious to determine from inside a kernel, but I found some code that shows how to do it.
Also added some module-level documentation outlining what's going on and why.
> pywwt/jupyter_server.py: fix file service in JupyterHub contexts

- lib/wwt.js
- pywwt/core.py
- pywwt/jupyter.py
- pywwt/layers.py
(This PR is cumulative on #216)
The main goal here is to add controls to the Jupyter widget so that the user can interactively tune the image stretch parameters straight in their notebook.
I set this up so that the Qt version of the widget should be unaffected.
I also ran into some issues with hidden JupyterLab widget views that look pretty thorny; I have some lengthy commit messages describing what I found and a workaround I put into place.
> Work on image-display user experience

- CHANGES.rst
- docs/conf.py
- pywwt/imagery.py
There's no real reason to keep the initial restriction of having only top-level surveys in the available imagery layers, so this is a small fix to make sure we expose all of them:
```
In [5]: wwt.available_layers                                                                                                                           
Out[5]: 
['2MASS: Catalog (Synthetic, Near Infrared)',
'2MASS: Two Micron All Sky Survey (Synthetic, Near Infrared)',
'2Mass: Imagery (Infrared)',
'Big Picture (Optical)',
'Black Sky Background',
'Bonn 1420 MHz Survey (Radio)',
'CGRO Compton Telescope: 3 channel data (Gamma)',
'COBE DIRBE (Infrared)',
'COBE DIRBE Annual Average Map (Infrared)',
'COBE DIRBE Zodi-Subtracted Mission Average (Infrared)',
'Digitized Sky Survey (Color)',
'EGRET Hard (Gamma)', …
```
> Include all available imagery layers

- docs/annotations.rst
- pywwt/annotation.py
- pywwt/core.py
- pywwt/layers.py
- pywwt/nbextension/static/interactive_figure/index.html
- pywwt/nbextension/static/interactive_figure/interactive_figure.js
- pywwt/solar_system.py
- pywwt/tests/test_serialization.py
Initial implementation of #200. This allows the user to save most of the current state of their WWT widget by calling the save_as_html_bundle function on the widget and specifying a folder or zip file destination. There is still functionality that would be good to add to the feature, some of which is listed below:
* Allowing users to name the exported csv and fits files with a nice interface (this pull request names the data files with the layer id)
* Better handling of errors when loading data:
* Retry loading depending on returned error.
* Better formatted way to display error messages.
* Add support for camera rotation and angle (and potentially add the ability to change these in python code)
* Potentially adding the option for the user to embed table data in the configuration JSON …
> Interactive Figure Proof of Concept

- .gitignore
- .travis.yml
- appveyor.yml
- docs/installation.rst
- package.json
- pywwt/__init__.py
- setup.py
- webpack.config.js
A bunch of polish of the Jupyter packaging based on my adventures with a fresh Miniconda install. Note that JupyterLab 1.0 just came out a couple of weeks ago.
> Jupyter polish

- RELEASE.rst
Mention updating the `stable` branch to update the ReadTheDocs docs. Also mention creating a new release on GitHub.
Finally, recommend a workflow in which the release commits are submitted via a pull request, so that that there is a CI run on the release candidate commit and the HEAD commit that keeps master at a development version.
> RELEASE.rst: tweak the release notes

- pywwt/imagery.py
This is a small adjustment to the foreground and background imagery layer naming scheme that helps names appear correctly in Jupyter. The intended behavior was that layers with the same shortened name (e.g. our 5 Fermi layers) would have object names in `wwt.imagery` like `fermi`, `fermi1`, `fermi2`, `fermi3`, etc.
This was the case in Qt, but in Jupyter they appeared as `fermi`, `fermi1`, `fermi12`, `fermi123`, etc. This PR fixes that error for me.
> Adjust imagery naming in Jupyter

- setup.py
For whatever reason, the package build reads in README.rst such that it expects it to be ASCII encoded, leading to an error if there's any Unicode. Use io.open and specify the encoding manually to make sure this doesn't happen.
> setup.py: fix package build on BinderHub

- docs/layers.rst
- docs/settings.rst
- docs/views.rst
I documented the additions I made in #187 -- time series capabilities in `TableLayer`s and `wwt.get_current_time()`.
> Updated docs to reflect time series additions

- CHANGES.rst
- pywwt/layers.py
This is a companion to https://github.com/WorldWideTelescope/pywwt/pull/223 that makes use of the improvements in the web client SDK in https://github.com/WorldWideTelescope/wwt-web-client/pull/237 to allow efficient size scaling of points by attributes.
This results in performance enhancements when changing e.g. the min/max for the size scaling on the Python side since we no longer keep sending the full data from Python to JS. Consider the following example with the original code before this PR:
```python
In [1]: from pywwt.qt import WWTQtClient  
...: %gui qt                                                                  
...: wwt = WWTQtClient(block_until_ready=True)  
...: from astropy.table import Table                                          
...: table = Table() …
```
> Make use of fast size scaling in SDK

- CHANGES.rst
- pywwt/jupyter.py
- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
This is a companion PR to https://github.com/WorldWideTelescope/wwt-web-client/pull/244 - it adds a ``cmap`` property for image layers, and also exposes it in the controls widgets for the image layer.
This can be reviewed, but shouldn't be merged until https://github.com/WorldWideTelescope/wwt-web-client/pull/244 is also merged. The tests might fail for now as a result.
> Allow image colormap to be set

- CHANGES.rst
- docs/installation.rst
- pywwt/layers.py
- pywwt/nbextension/static/wwt_json_api.js
This PR switches the colormapping of points to use the API that is being proposed in https://github.com/WorldWideTelescope/wwt-web-client/pull/238. For colormaps that are supported by the web client (which we can easily expand the list of), we use the new efficient route, while for other colormaps, we use the old approach. The following example shows that the old approach is more than 1000x slower for a 50,000 row dataset (``RdBu`` shows the old approach):
```python
In [1]: from pywwt.qt import WWTQtClient   
...: %gui qt                                                                   
...: wwt = WWTQtClient(block_until_ready=True)   
...: from astropy.table import Table                                           
...: table = Table() …
```
> Make use of fast colormapping in SDK

- pywwt/layers.py
- pywwt/nbextension/static/interactive_figure/interactive_figure.js
- pywwt/tests/test_serialization.py
When we added colormap selection to images, the new parameter wasn't added to the set of fields that got serialized to JSON. Just went ahead and fixed it rather than filing an issue.
Not documented since it's part of serialization Just Working. Covered in CHANGES.rst as part of the cmap addition.
> Include image colormap selection in JSON serialization

- lib/wwt.js
- package.json
This should in principle fix compatibility with Jupyter Lab 2.0 once ipyevents is fixed and a new version of ipywidgets is released. It still doesn't work for me but I think (based on the error messages) this is an ipyevents issue, or related dependency.
> Fix compatibility with Jupyter Lab 2.0

- frontend/lib/wwt.js
- pywwt/nbextension/static/wwt.html
- pywwt/tests/test_qt_widget.py
Try to fix up the Jupyter widget behavior in the presence of multiple views, and the fact that views can be reset more or less at whim since hiding a widget view causes the underlying WWT iframe to be reset.
- Not really :-( This area of functionality doesn't really have test infrastructure right now.
- No behavior changes in standard usage; this should basically just cause more robust/reliable behavior in funky situations
> Work on improving Jupyter behavior with multiple views and view resets

- pywwt/nbextension/static/wwt.html
It looks like the Qt JavaScript interpreter on macOS doesn't like the trailing comma in our function call, causing the embedded webpage to break. If correct this is a little scary in terms of what it means for our ability to use remotely advanced JS constructs, but let's see if this keeps things going for now.
Also some general whitespace futzing, but the key change is to the `startMode` line.
> pywwt/nbextension/static/wwt.html: remove trailing comma

- frontend/package.json
- pywwt/annotation.py
It looks like we need this for the ipywidget to work in JupyterLab 3.x.
> frontend/package.json: proclaim compatibility with @jupyter-widgets/base 4.x

- pywwt/jupyter.py
- pywwt/jupyter_server.py
Prototype-quality support for connecting pywwt to the freestanding WWT JupyterLab application, as opposed to individual "widgets" associated with specific notebooks.
In order to be able to share image data with this application, we need to make sure to set CORS data-sharing headers for the files that we serve up.
Docs and tests coming, but I want to make a release with the initial support to test out how everything hangs together in production.
> pywwt/jupyter.py: add support for the JupyterLab application

- setupbase.py
ReadTheDocs builds aren't working due to a very old npm:
https://github.com/readthedocs/readthedocs.org/issues/8249
N/A
> setupbase.py: try this to fix ReadTheDocs

- ci/azure-deployment.yml
ReadTheDocs wants to monitor a branch or tag named "stable" for the same-named version of the docs that it publishes. So, set up the CI to update it sensibly.
N/A
> ci/azure-deployment.yml: update a new stable branch for ReadTheDocs

- pywwt/core.py
Explicitly make the `_serve_file` abstract function part of the base WWT client, and add an exception type for detecting when file service isn't available.
> pywwt/core.py: explicitly make `_serve_file` a common API

- .gitignore
- frontend/lib/widget.js
- frontend/package.json
- frontend/pywwt-export.js
- pywwt/core.py
- pywwt/jupyter.py
- pywwt/jupyter_server.py
- pywwt/solar_system.py
- pywwt/tests/test_serialization.py
Firstly, here we start bundling the research app with the Jupyter extension. While the native JupyterLab extension loads the app directly from its hosted WWT instance, there are valid cases to use a bundled version. In particular, I've seen at least one example (SciServer) where a cross-origin app isn't allowed to access data from a Jupyter server.
Secondly, we port the Jupyter widget implementation (i.e., ipywidgets) to use the app instead of the hand-coded HTML implementation. This turns out to be somewhat involved since the app needed some upgrading to handle the ipywidgets setup, which can involve both multiple clients (multiple widgets) and multiple apps (multiple views per widget).
> Bundle the research app with the Jupyter extension and port the ipywidgets implementation to use it

- frontend/pywwt-export.js
- pywwt/qt.py
Closes #306.
(This should add test coverage but I am being a bad lazy person :-()
> Restore the wwt_ready Qt signal

- frontend/lib/widget.js
- frontend/package.json
- pywwt/core.py
- pywwt/jupyter.py
- pywwt/layers.py
This PR supersedes #289, building on the improved foundation that I've been working on. Namely:
- Unifying all modes to to use the "app" as the viewer backend
- Here, adding foundational support for async operations
The async support turns out to require an extremely gross hack of the Jupyter kernel framework but I believe that the approach is fundamentally OK, if hacky and fragile.
> Updated HiPS catalog support

- ci/azure-sdist.yml
- pywwt/layers.py
- pywwt/qt.py
Address #309 just by bumping out the app liveness deadline.
Also fix an error caused by upgrading to Astropy 4.3, which I just noticed.
> Address #309

- pywwt/imagery.py
While attempting to load [this WTML collection](https://wwtambassadors.org/files/wwtambassadors/files/buacgalaxyhistoryuniverse.wtml), I noticed that `pywwt` is currently unable to parse a collection where at least one entry has a missing `ThumbnailUrl` entry.
If `ThumbnailUrl` is not present, then `survey.find('ThumbnailUrl')` is `None`, and so `survey.find('ThumbnailUrl').text` yields an `AttributeError`. This PR fixes that issue by first checking whether or not the call to `find` returned `None`.
The `or None` at the end of line 35 is to retain the previous behavior of an empty string (which is falsy) being converted to `None`.
FWIW, this file loads correctly in the web client (where the two entries without thumbnail urls, UGC 2369 and 4C 73.08, are given a default thumbnail).
> Allow for WTML parsing when ThumbnailURL is absent

- pywwt/jupyter_server.py
This change will ease migration as we start switching to the WWT Kernel Data Relay for hosting kernel data files.
Even once the KDR is everywhere, there is still a value in having `pywwt` act as a Jupyter *server* extension (which it does in addition to being a *notebook* extension and a *JupyterLab* extension). This is because some Jupyter(Lab) setups deny all cross-origin requests, which means that we have to host a local copy of the research app for it to load any data from kernels. Since pywwt already bundles the research app, it's a natural place to do that, and will remain so even if everyone uses the KDR, because it can host that local copy even if no kernels are running. But to prevent clashes between older and newer versions, we want to use a separate URL namespace. So here we …
> Aid KDR migration by adding support for serving /wwtstatic/ URLs

- ci/azure-build-and-test.yml
- docs/installation.rst
- pywwt/jupyter_relay.py
When testing the new HiPSgen tiling code, I ran into at least one variant of the KDR issues reported by @imbasimba . 404s weren't being handled properly because pywwt wasn't including sequence numbers in its error messages.
Also tidy up some documentation infrastructure in the aftermath of #318 and the hotfixes pushed straight to master.
> Fix Kernel Data Relay sequence numbers on errors

- pywwt/jupyter_relay.py
I have not found the root cause of this issue, but increasing the chunk size to something ridiculously high, like 8MB should make this error extremely unlikely.
What I found during the investigation is that the messages are all sent correctly, but only the first 2000 are received by KDR.
In some rare instances, when multiple requests are fired almost simultaneously, less than 2000 are received. This has led me to believe that the limit is on the receiving end, so we cannot just make sure that every single request is less than 2000 messages, since all the requests are fighting for the same 2000 spots. So I felt like it is safest to up the chunk size to something very, very high. At least until the root issue is found and resolved.
> Increased jupyter-relay chunk size to 8MB

- pywwt/layers.py
- pywwt/utils.py
- setup.py
Adapted add_image_layer for new toasty functionality (including HiPSgen) https://github.com/WorldWideTelescope/toasty/pull/69
- hdu_index can now also be a list
- Previous usage of hdu_index with non-tiled FITS caused KeyError by ImageLayer's validate_traits. Now fixed by a kwargs.pop. 
@pkgw Can you think of a better way of dealing with the toasty keywords? Right now, they are manually popped in _remove_toasty_keywords, which doesn't feel too stable. At the same time validating the traits sent to ImageLayer seems like a useful thing to do. And exposing all toasty settings explicitly in the add_image_layer does not seem optimal either.  Let me know what you think.
> More add layer options

- docs/api/pywwt.annotation.rst
- docs/api/pywwt.annotation_.rst
- docs/index.rst
I'm not entirely sure why there are two pywwt.annotation.rst, but the are fighting each other since they have the same name with different capitalization (pywwt.**a**nnotation.rst vs pywwt.**A**nnotation.rst)
So I deleted one, but maybe there is a better solution?
> Removed pywwt.annotation.rst

- pywwt/layers.py
- setup.py
- Image layer display name is now based on the file name
- The display can also be manually set with the new `name` parameter
- Using imageset suggested cuts, data_min & data_max from https://github.com/WorldWideTelescope/wwt_data_formats/pull/44 and https://github.com/WorldWideTelescope/toasty/pull/71
- Repaired  `imageset.controls` for untiled FITS, by setting `_data_min` and `_data_max`
- Undocumented `force_untiled` parameter added. This is useful for us developers, but I imagine this parameter will not be used by real users
> Image layer cuts and display name

- pywwt/layers.py
- pywwt/tests/test_serialization.py
This PR allows the `time_decay` property of a table layer to be serialized - currently, using `_serialize_state` if the WWT widget is displaying a table layer will throw an error as it doesn't know how to serialize an astropy `Quantity`. The conversion is the same as is used in `_on_trait_change` [here](https://github.com/WorldWideTelescope/pywwt/blob/master/pywwt/layers.py#L1305).
The motivation is to allow `save_as_html_bundle` to work, with https://github.com/glue-viz/glue-wwt/pull/62 being a particular case where this functionality would be used. It would be nice to have the exported bundle use the research app, but I suspect that will take a nontrivial amount of effort.
> Allow time_decay attribute of layers to be serialized

- pywwt/layers.py
This PR adds the ability to select whether or not a table layer is selectable - basically, exposing the functionality from https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/183. As in that PR, allowing client applications to make layers non-selectable should help performance when there are a lot of points, with `glue-wwt` being one example of an application that can benefit from having layers be non-selectable most of the time. To make this possible, I've added a boolean `selectable` traitlet to the table layer class. Since selectability is a property at the research app level, rather than of the engine layer, I've set `wwt=None` in the traitlet metadata.
> Allow toggling whether a table layer is selectable

- ci/azure-deployment.yml
- ci/azure-sdist.yml
- ci/zenodo.json5
- pywwt/_version.py
- pywwt/jupyter_server.py
- setup.py
Add automated Zenodo deposition to mint DOIs for pywwt releases.
Minting DOIs implies maintaining a formal author list. For that, I've included everyone who's ever committed to the repository, alphabetically by family name. But I won't list people without their permission. **If you'd like to be included as an author, please comment on this PR to that effect**, and review what I've put for your name, affiliation, and ORCID:
It might take me a couple of tries to get the CI/CD automation to fully work, but hopefully it will be straightforward since I've gotten it going for the Cranko tool itself.
> Add Zenodo auto-deposit for DOI registration

- pywwt/layers.py
- pywwt/tests/test_serialization.py
This PR fixes a bug in the interactive figure export where named colormaps are not exported correctly. This is a pretty straightforward change, we just need to make sure to account for all of the relevant settings, which I did by mimicking the logic [here](https://github.com/WorldWideTelescope/pywwt/blob/master/pywwt/layers.py#L1126).
Also, I changed `"_colorMap"` to `"colorMap"` in the other two cases because using `"_colorMap"` doesn't call the setter correctly (since it's `set_colorMap` rather than `set__colorMap`).
> Update interactive figure export to account for named colormaps

- setupbase.py
Building with Python 3.11 currently fails at
```python
File "/Users/derek/git/pywwt/setupbase.py", line 613, in _compile_pattern
return re.compile(res, flags=flags).match
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/lib/python3.11/re/__init__.py", line 227, in compile
return _compile(pattern, flags)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/lib/python3.11/re/__init__.py", line 294, in _compile
p = _compiler.compile(pattern, flags)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/lib/python3.11/re/_compiler.py", line 743, in compile
p = _parser.parse(p, flags)
^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/lib/python3.11/re/_parser.py", line 980, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/lib/python3.11/re/_parser.py", line …
```
> Move re-flag in `_translate_glob` to front to build with Python 3.11

- pywwt/qt.py
- setup.py
@Carifio24 I tested out your Qt6 fix suggested in https://github.com/WorldWideTelescope/pywwt/issues/343 and it works fine when using PyWWT inside glue, so from my perspective, this is a sufficient fix.
> Fix compatibilty with Qt6

- .check_enabled.py
- .readthedocs_env.yml
- ci/azure-build-and-test.yml
- docs/installation.rst
- pywwt/core.py
- pywwt/jupyter_relay.py
- pywwt/jupyter_server.py
With all the colors getting exposed in #355, I accidentally gave the ecliptic grid the wrong starting color (maybe got it mixed up with the ecliptic color?) - it should be [green](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Settings.cs#L358), rather than blue, to match the engine. This PR fixes that.
> Update ecliptic grid color default

- .readthedocs.yaml
- .readthedocs_env.yml
Previous RTD build attempt failed due to the Conda process taking too much memory! I have tried to turn on RTD builds during pull requests, so hopefully we can work on fixing this without having to merge to the main branch to test each change.
> Try to fix ReadTheDocs again

- frontend/lib/widget.js
This PR aims to make the pywwt widget compatible with ipywidgets 8.x, which currently seems to not be the case. I was trying to use the Jupyter widget in a glue-wwt context together with some of the new widgets from ipywidgets 8 but kept getting the following error:
```
Model class 'WWTModel' from module 'pywwt' is loaded but can not be instantiated
TypeError: r._deserialize_state is not a function
at f._make_model (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7933)
```
After some investigation, it seems that we need to update our widget JS to use ES6 class notation (see [here](https://ipywidgets.readthedocs.io/en/latest/migration_guides.html#backbone-extend)), which is the content of this PR. With …
> Compatibility with ipywidgets 8.x

- ci/azure-build-and-test.yml
- ci/azure-deployment.yml
- ci/azure-sdist.yml
- pywwt/core.py
Cranko still needs updating to adapt to Zenodo's API changes, but we want to get a release out. So, like in `wwt_data_formats`, let's just disable the registration until that gets fixed. Such is life.
> ci: temporarily disable Zenodo so we can get a release out

- ci/azure-build-and-test.yml
- setup.py
Downstream in `glue-wwt` we're trying to make `qtpy` be an optional dependency (https://github.com/glue-viz/glue-wwt/issues/111) so that it doesn't need to be installed to use the WWT Jupyter viewer. To help make that possible, this PR makes `qtpy` an optional dependency of `pywwt`, moving it to the `qt` and `qt6` install options.
The [documentation](https://github.com/WorldWideTelescope/pywwt/blob/master/docs/installation.rst?plain=1#L221) already makes it sound like `qtpy` is an optional dependency, so I don't think it needs to be changed at all?
> Make qtpy dependency optional

- pywwt/layers.py
Try to make sure we work with Numpy 2!
> Fixups for Numpy 2 compatibility

- ci/azure-build-and-test.yml
Currently the Python 3.9 and 3.10 jobs in the Linux CI are failing with segmentation faults, which I think is related to their not being able to recognize OpenGL. This PR is an attempt to think that. I suspect that this will require a good bit of iteration.
> Fix OpenGL issues in Linux CI

- setupbase.py
We currently have a reference to the `pipes` package in our `setupbase` utilities, has been deprecated since Python 3.11 and has now been removed in 3.13. Our only need for `pipes` is a single use of `pipes.quote`, which was [already being imported from `shlex`](https://github.com/python/cpython/blob/3.12/Lib/pipes.py#L66), so this PR replaces it with `shlex.quote`.
FWIW, I noticed this issue in a downstream `glue-wwt` [CI job](https://github.com/glue-viz/glue-wwt/actions/runs/13123865470/job/37950729027).
> Replace pipes with shlex in setupbase

- pywwt/layers.py
The Read the Docs job is failing because we use `np.unicode_`, which no longer exists in numpy 2. This PR updates to use `np.str_`, which was equivalent to `np.unicode_` in numpy 1.x and still exists in numpy 2.
> Use np.str_ for numpy 2 compatibility
